export const LOGIN_MODAL_OPEN = 'LOGIN_MODAL_OPEN';
export const LOGIN_MODAL_CLOSE = 'LOGIN_MODAL_CLOSE';
export const EDIT_PRODUCT_MODAL_OPEN = 'EDIT_PRODUCT_MODAL_OPEN';
export const EDIT_PRODUCT_MODAL_CLOSE = 'EDIT_PRODUCT_MODAL_CLOSE';
export const SET_PRODUCT = 'SET_PRODUCT';
export const OPEN_AUTHORIZATION_POPUP = 'OPEN_AUTHORIZATION_POPUP';
export const HIDE_AUTHORIZATION_POPUP = 'HIDE_AUTHORIZATION_POPUP';
