export const ADD_PRODUCT_TO_FAVORITE = 'ADD_PRODUCT_TO_FAVORITE';
export const DELETE_PRODUCT_FROM_FAVORITE = 'DELETE_PRODUCT_FROM_FAVORITE';
export const FAVORITES_FROM_LOCAL_STORAGE = 'FAVORITES_FROM_LOCAL_STORAGE';
export const FAVORITE_PRODUCT_CHANGE_ORDER = 'FAVORITE_PRODUCT_CHANGE_ORDER';
export const SHOW_GRID = 'SHOW_GRID';
