export const SET_SEARCH_PRODUCTS = 'SET_SEARCH_PRODUCTS';
export const GET_FILTERED_PRODUCTS = 'GET_FILTERED_PRODUCTS';
export const GET_ALL_SEARCH_PRODUCTS = 'GET_ALL_SEARCH_PRODUCTS';
export const PAGINATE_PAGE_NUMBER = 'PAGINATE_PAGE_NUMBER';
export const SET_SEARCH_PRODUCTS_PER_PAGE = 'SET_SEARCH_PRODUCTS_PER_PAGE';
export const CLEAR_SEARCH_PRODUCTS = 'CLEAR_SEARCH_PRODUCTS';
export const SORT_SEARCH_PRODUCTS = 'SORT_SEARCH_PRODUCTS';
