export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_CURRENT_CAREGORY = 'SET_CURRENT_CAREGORY';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_PER_PAGE = 'SET_PER_PAGE';
export const SET_CURRENT_QUERY = 'SET_CURRENT_QUERY';
export const SET_FLAG_IN_CART = 'SET_FLAG_IN_CART';
export const SET_CURRENT_PRODUCTS_ARR = 'SET_CURRENT_PRODUCTS_ARR';
