/* eslint-disable operator-linebreak */
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CAREGORY';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_PER_PAGE = 'SET_PER_PAGE';
export const SET_CURRENT_QUERY = 'SET_CURRENT_QUERY';
export const SET_FLAG_IN_CART = 'SET_FLAG_IN_CART';
export const SET_CURRENT_PRODUCTS_ARR = 'SET_CURRENT_PRODUCTS_ARR';
export const SET_SORT_BY = 'SET_SORT_BY';
export const SHOW_GRID = 'SHOW_GRID';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const GET_PRODUCTS_FROM_LOCAL_STORAGE =
  'GET_PRODUCTS_FROM_LOCAL_STORAGE';
export const SET_CATEGORY_FOR_BREADCRUMBS = 'SET_CATEGORY_FOR_BREADCRUMBS';
export const GET_CATEGORY_FROM_LOCAL_STORAGE =
  'GET_CATEGORY_FROM_LOCAL_STORAGE';
export const GET_PER_PAGE_FOR_FILTER = 'GET_PER_PAGE_FOR_FILTER';
export const FILTERED_PRODUCTS_FOR_PAGINATION = 'FILTERED_PRODUCTS_FOR_PAGINATION';
export const SET_CURRENT_BRANDQUERY = 'SET_CURRENT_BRANDQUERY';
