export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const CART_FROM_LOCAL_STORAGE = 'CART_FROM_LOCAL_STORAGE';
export const CART_INCREMENT = 'CART_INCREMENT';
export const CART_DECREMENT = 'CART_DECREMENT';
export const SET_TOTAL_SUM_CART = 'SET_TOTAL_SUM_CART';
export const SET_TOTAL_COUNT_CART = 'SET_TOTAL_COUNT_CART';
export const SET_POPUP_FALSE = 'SET_POPUP_FALSE';
