export const SET_PRODUCTS = 'SET_PRODUCTS';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const MODAL_REMOVE_PRODUCT = 'MODAL_REMOVE_PRODUCT';
export const MODAL_REMOVE_PRODUCT_CLOSE = 'MODAL_REMOVE_PRODUCT_CLOSE';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const SET_CATALOG = 'SET_CATALOG';
